Webpack Client and Server
coq-community/vscoq pull request #266
Opened 2021-12-25 18:31 UTC by fakusb

The client and server are now webpacked. To make this all work out, I had to split the single 'out' folder into three `out` folders, next to the already existing three `src` folders. ALso, now a few more files are ignored when bundling the extension as `.vsix` file for publishing in the marketplaces (`.vscodeignore`).

The debugging of the extension itself works as before, including breakpoints and sourcemaps.

The extension now loads ~20% faster (from a startup time of 100 ms to 80ms), and is smaller (312kB `.vsix` file instead of >5MB), and consists of a lot less files (The warning upon packaging the vsix file is now gone, so the nudging from microsoft to webpack worked for me).

And when we want to support vscode-server, webpacking will be needed (so this is towards #257 ).

2022-02-23 11:47 UTC, artagnon requested changes
Nice overall. Should have minimal conflicts with #276.

2022-02-23 11:47 UTC, artagnon commented on Makefile
> +	rm -rf node_modules client/out server/out html_views/out
This line can be replaced by a terse `git clean -dfx`, if the `.gitignore` is correct.

2022-02-23 11:47 UTC, artagnon commented on package.json
> +    "watch": "webpack --watch --mode none --config webpack.config.js",
I would drop "compile:server", "compile:client", and "compile:html_views", as webpack is smart enough to compile only what's necessary: a `webpack` invoked from the toplevel directory should do whatever is necessary, and it's unlikely that any developer would invoke any of these three build targets individually.

Further, `--config webpack.config.js` can be stripped, as webpack automatically looks for a `webpack.config.js` by default. Perhaps add `--devtool hidden-source-map` to "package", and drop the extraneous `--mode none`, as the common config specifies this mode.

Finally, I might be tempted to drop the "package:dev" target, as it's unlikely to be used directly.

2022-02-23 11:47 UTC, artagnon commented on package.json
> +    "clean": "rimraf client/out && rimraf html_views/out && rimraf server/out"
This is duplicating code from the Makefile and unnecessarily adding a dependency.

2022-02-23 11:47 UTC, artagnon commented on tsconfig.json
> +    //"rootDir": "src",
Please strip these commented out lines.

2022-02-23 11:47 UTC, artagnon commented on server/tsconfig.json
> +    "target": "es6",
Consider factoring out these two lines into `tsconfig.base.json`.

2022-02-23 11:47 UTC, artagnon commented on server/tsconfig.json
> +    "sourceMap": true,
Consider factoring out these two lines too.

2022-02-23 11:47 UTC, artagnon commented on server/tsconfig.json
> +    "tsBuildInfoFile": "out/tsconfig.tsBuildInfoFile",
Very nice!

2022-02-23 11:47 UTC, artagnon commented on shared.webpack.config.js
> +		//},
Please remove this dead code.

2023-02-19 09:14 UTC, thery commented
@fakusb @Blaisorblade @huynhtrankhanh @4ever2. I'd like to include this to the next release.  This is far beyond my competence, :disappointed: . Any ideas how to rebase this?

2023-02-19 15:56 UTC, 4ever2 commented
@thery I rebased this and it seems to work okay after a few minor fixes. But still need to test it more.

https://github.com/4ever2/vscoq/tree/webpack

2023-02-19 16:51 UTC, thery commented
@4ever2  Thanks a lot. I think it is worth being merged. I will test it.

2023-03-01 20:06 UTC, thery commented
This is superseded by #411

2023-03-01 20:06 UTC, closed without merging