Adapt w.r.t. coq/coq#18652.
coq-community/vscoq pull request #722
Opened 2024-02-09 22:22 UTC by ppedrot

2024-02-10 07:33 UTC, gares requested changes
This change breaks 8.19 and 8.18.
We use ppx_optcomp that gives you ifdefs at the top level. There are a few examples around already, please follow that style

2024-02-10 07:51 UTC, gares commented
Example
https://github.com/coq-community/vscoq/blob/4eefe13822617d99de2e8bb5430f04209829effa/language-server/dm/parTactic.ml#L63

2024-02-10 13:40 UTC, ppedrot commented
Fixed.

2024-02-11 07:44 UTC, gares commented
@rtetley we should not fail fast in the matrix. Here coq master does not include the change yet, but we still want to test 8.18 and 8.19

2024-02-11 07:46 UTC, gares approved these changes

2024-02-11 07:47 UTC, gares commented
Also the opamfile ditches .dev, so we test coq 8.19 twice (the dev job downgrades it)

2024-02-11 07:48 UTC, gares commented
We should add a ... | = "dev" in the expression

2024-02-11 15:03 UTC, gares commented
Sorry for pushing here ci changes, but this is the first PR after the ppx_optcomp change, hence we need to streamline the process

2024-02-11 15:33 UTC, gares commented on .github/workflows/ci.yml
> +        opam pin add coq-core ${{ matrix.coq }}
```suggestion
        if [ "${{ matrix.coq }}" = "dev" ]; then opam install coq-core.dev; else opam pin add coq-core ${{ matrix.coq }}; fi
```

2024-02-11 15:51 UTC, gares commented
looks finally ok, the only jobs failing are the ones about coq master, since these are tested by Coq ci (against the PR requiring this change). The jobs about stable versions are green.

@rtetley the CI changes can be pushed to master, IMO. Dunno if we want the dev jobs to be in allowed-failure, or not. I did also spot a 8.18 value in the windows job, IIRC. Not sure it is actually used.

2024-02-11 15:58 UTC, ppedrot commented
There are unrelated changes in this PR, maybe it should still be marked as a draft while the upstream Coq PR is not merged...

2024-02-19 11:31 UTC, merged