[coq] Adapt to coq/coq#19187
coq-community/vscoq pull request #783
Opened 2024-06-08 16:28 UTC by ejgallego

2024-06-09 15:30 UTC, gares requested changes
Please use outcome, that is put the change in a [%%if...] block.

2024-06-10 12:01 UTC, SkySkimmer commented on language-server/dm/documentManager.ml
> +  | Some { synterp_state } -> Vernacstate.Synterp.parsing synterp_state
```suggestion
[%%if coq = "8.20"]
  | None -> Vernacstate.(Synterp.parsing st.init_vs.synterp)
  | Some { synterp_state } -> Vernacstate.Synterp.parsing synterp_state
[%%else]
  | None -> st.init_vs.Vernacstate.synterp.parsing
  | Some { synterp_state } -> synterp_state.Vernacstate.Synterp.parsing
[%%endif]
```

2024-06-10 13:04 UTC, SkySkimmer commented on language-server/dm/documentManager.ml
>    Vernacstate.Parser.parse st entry pa
```suggestion
[%%if coq = "8.20"]
let parse_entry st pos entry pattern =
  let pa = Pcoq.Parsable.make (Gramlib.Stream.of_string pattern) in
  let st = match Document.find_sentence_before st.document pos with
  | None -> Vernacstate.(Synterp.parsing st.init_vs.synterp)
  | Some { synterp_state } -> Vernacstate.Synterp.parsing synterp_state
  in
  Vernacstate.Parser.parse st entry pa
[%%else]
let parse_entry st pos entry pattern =
  let pa = Pcoq.Parsable.make (Gramlib.Stream.of_string pattern) in
  let st = match Document.find_sentence_before st.document pos with
  | None -> st.init_vs.Vernacstate.synterp.parsing
  | Some { synterp_state } -> synterp_state.Vernacstate.Synterp.parsing
  in
  Vernacstate.Parser.parse st entry pa
[%%endif]
```

2024-06-10 13:31 UTC, merged

2024-06-10 13:35 UTC, ejgallego commented
Thanks @SkySkimmer